# lightning.pytorch==2.5.0.post0
seed_everything: 21
trainer:
  devices: 1
  logger:
    class_path: StrictWandbLogger
    init_args:
      project: "VirtualCRISPR"
      name: "contrastive-unsummarized"
      save_dir: "./runs"
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val_loss"
        mode: "min"
        patience: 15
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: "epoch"
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: "val_loss"
        mode: "min"
        save_last: "link"
  max_epochs: 100
  log_every_n_steps: 1
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.001
    weight_decay: 0.01
lr_scheduler:
  class_path: lightning.pytorch.cli.ReduceLROnPlateau
  init_args:
    monitor: "val_loss"
    patience: 5
model:
  class_path: LightningContrastiveModel
  init_args:
    exp_input: 9216
    exp_reduction: 3
    exp_layers: 2
    gene_input: 3072
    gene_reduction: 2
    gene_layers: 2
    shared_dim: 512
data:
  data_dir: "./data"
  use_summarized: False
  hits_only: True
  batch_size: 8192
  num_workers: 2
  validation_screens:
  - 1545
  - 613
  - 316
  - 153
  - 1906
